"""Service for sending AI-generated summaries via email using Resend."""

import re

import resend

from app.config import settings

resend.api_key = settings.resend_api_key


def _markdown_to_html(text: str) -> str:
    """
    Simple markdown-to-HTML converter for the email body.
    Handles headers, bold, bullet points, and paragraphs.
    """
    lines = text.split("\n")
    html_lines: list[str] = []
    in_list = False

    for line in lines:
        stripped = line.strip()

        # Close list if we're no longer in one
        if in_list and not stripped.startswith(("- ", "* ", "• ")):
            html_lines.append("</ul>")
            in_list = False

        if not stripped:
            html_lines.append("<br>")
            continue

        # Headers
        if stripped.startswith("### "):
            html_lines.append(f"<h3>{stripped[4:]}</h3>")
        elif stripped.startswith("## "):
            html_lines.append(f"<h2>{stripped[3:]}</h2>")
        elif stripped.startswith("# "):
            html_lines.append(f"<h1>{stripped[2:]}</h1>")
        # Bullet points
        elif stripped.startswith(("- ", "* ", "• ")):
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
            content = stripped[2:]
            html_lines.append(f"<li>{content}</li>")
        else:
            html_lines.append(f"<p>{stripped}</p>")

    if in_list:
        html_lines.append("</ul>")

    html = "\n".join(html_lines)
    # Bold text
    html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
    return html


def send_summary_email(recipient: str, summary: str, filename: str) -> dict:
    """
    Send the AI-generated summary to the recipient via Resend.

    Args:
        recipient: Email address to send the summary to.
        summary: The AI-generated sales summary (markdown text).
        filename: Original filename for context in the email subject.

    Returns:
        Resend API response dict.
    """
    html_body = f"""
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 680px; margin: 0 auto;
                padding: 32px; background: #ffffff; border-radius: 12px;">
        <div style="border-bottom: 3px solid #6366f1; padding-bottom: 16px; margin-bottom: 24px;">
            <h1 style="color: #1e1b4b; margin: 0; font-size: 24px;">
                📊 Sales Insight Report
            </h1>
            <p style="color: #6b7280; margin: 4px 0 0; font-size: 14px;">
                Auto-generated analysis for <strong>{filename}</strong>
            </p>
        </div>

        <div style="color: #374151; line-height: 1.7; font-size: 15px;">
            {_markdown_to_html(summary)}
        </div>

        <div style="margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb;
                    color: #9ca3af; font-size: 12px; text-align: center;">
            Generated by <strong>Sales Insight Automator</strong> · Powered by Rabbitt AI
        </div>
    </div>
    """

    params: resend.Emails.SendParams = {
        "from": settings.from_email,
        "to": [recipient],
        "subject": f"📊 Sales Insight Report — {filename}",
        "html": html_body,
    }

    return resend.Emails.send(params)
